/**
 * POA&M number generation and validation.
 *
 * Format: V-{SYSTEM_SHORT_CODE}-{ZERO_PADDED_SEQUENCE}
 * Example: V-ACME-0042
 *
 * The sequential number is generated by the database (see migration), not the client.
 * This module provides the formatting and parsing helpers.
 */

import { z } from "zod";

/**
 * Formats a POA&M number from its components.
 *
 * @param shortCode  System short code (e.g. "ACME"). Uppercased automatically.
 * @param sequence   Sequential integer (must be > 0).
 */
export function formatPoamNumber(shortCode: string, sequence: number): string {
  if (sequence <= 0 || !Number.isInteger(sequence)) {
    throw new RangeError(`POA&M sequence must be a positive integer, received ${sequence}`);
  }
  return `V-${shortCode.toUpperCase()}-${String(sequence).padStart(4, "0")}`;
}

/**
 * Parses a POA&M number back into its components.
 * Returns null if the format is invalid.
 */
export function parsePoamNumber(
  poamNumber: string
): { shortCode: string; sequence: number } | null {
  const match = /^V-([A-Z0-9]+)-(\d+)$/.exec(poamNumber);
  if (!match) return null;
  const [, shortCode, sequenceStr] = match;
  return {
    // The regex guarantees these are defined.
    shortCode: shortCode!,
    sequence: parseInt(sequenceStr!, 10),
  };
}

/**
 * Zod schema for validating a POA&M number string.
 */
export const PoamNumberSchema = z
  .string()
  .regex(/^V-[A-Z0-9]+-\d{4}$/, "POA&M number must match format V-CODE-NNNN");

/**
 * Zod schema for a system short code.
 * 2–10 characters, uppercase letters and digits only.
 */
export const SystemShortCodeSchema = z
  .string()
  .min(2, "Short code must be at least 2 characters")
  .max(10, "Short code must be at most 10 characters")
  .regex(
    /^[A-Z0-9]+$/,
    "Short code must contain only uppercase letters and digits"
  );
