/**
 * Supabase generated types.
 *
 * This file is generated by `npm run db:generate-types` and committed.
 * Do not edit by hand.
 *
 * Placeholder until a Supabase project is connected and migrations run.
 * Run: `supabase gen types typescript --local > types/supabase.ts`
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      organizations: {
        Row: {
          id: string;
          name: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          created_at?: string;
        };
      };
      users: {
        Row: {
          id: string;
          organization_id: string;
          role: "admin" | "issm" | "isso" | "engineer" | "auditor";
          full_name: string;
          created_at: string;
        };
        Insert: {
          id: string;
          organization_id: string;
          role?: "admin" | "issm" | "isso" | "engineer" | "auditor";
          full_name: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          role?: "admin" | "issm" | "isso" | "engineer" | "auditor";
          full_name?: string;
          created_at?: string;
        };
      };
      systems: {
        Row: {
          id: string;
          organization_id: string;
          name: string;
          short_code: string;
          fedramp_level: "Low" | "Moderate" | "High";
          authorization_date: string | null;
          ato_expiration: string | null;
          agency_sponsor: string | null;
          status: "active" | "sunset";
          poam_sequence: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          name: string;
          short_code: string;
          fedramp_level: "Low" | "Moderate" | "High";
          authorization_date?: string | null;
          ato_expiration?: string | null;
          agency_sponsor?: string | null;
          status?: "active" | "sunset";
          poam_sequence?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          name?: string;
          short_code?: string;
          fedramp_level?: "Low" | "Moderate" | "High";
          authorization_date?: string | null;
          ato_expiration?: string | null;
          agency_sponsor?: string | null;
          status?: "active" | "sunset";
          poam_sequence?: number;
          created_at?: string;
        };
      };
      scans: {
        Row: {
          id: string;
          system_id: string;
          scan_type: "os" | "webapp" | "database";
          scanner_name: string;
          scan_date: string;
          total_findings: number;
          uploaded_by: string;
          raw_file_url: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          system_id: string;
          scan_type: "os" | "webapp" | "database";
          scanner_name: string;
          scan_date: string;
          total_findings?: number;
          uploaded_by: string;
          raw_file_url?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          system_id?: string;
          scan_type?: "os" | "webapp" | "database";
          scanner_name?: string;
          scan_date?: string;
          total_findings?: number;
          uploaded_by?: string;
          raw_file_url?: string | null;
          created_at?: string;
        };
      };
      findings: {
        Row: {
          id: string;
          scan_id: string;
          system_id: string;
          plugin_id: string;
          title: string;
          description: string | null;
          cvss_score: number | null;
          severity: "high" | "moderate" | "low" | "informational";
          affected_asset: string;
          first_detected: string;
          last_detected: string;
          status:
            | "open"
            | "remediated"
            | "deviation_pending"
            | "deviation_approved"
            | "risk_accepted";
          created_at: string;
        };
        Insert: {
          id?: string;
          scan_id: string;
          system_id: string;
          plugin_id: string;
          title: string;
          description?: string | null;
          cvss_score?: number | null;
          severity: "high" | "moderate" | "low" | "informational";
          affected_asset: string;
          first_detected: string;
          last_detected: string;
          status?:
            | "open"
            | "remediated"
            | "deviation_pending"
            | "deviation_approved"
            | "risk_accepted";
          created_at?: string;
        };
        Update: {
          id?: string;
          scan_id?: string;
          system_id?: string;
          plugin_id?: string;
          title?: string;
          description?: string | null;
          cvss_score?: number | null;
          severity?: "high" | "moderate" | "low" | "informational";
          affected_asset?: string;
          first_detected?: string;
          last_detected?: string;
          status?:
            | "open"
            | "remediated"
            | "deviation_pending"
            | "deviation_approved"
            | "risk_accepted";
          created_at?: string;
        };
      };
      poam_items: {
        Row: {
          id: string;
          system_id: string;
          finding_id: string | null;
          poam_number: string;
          weakness_description: string;
          source: "scan" | "assessment" | "self_identified";
          severity: "high" | "moderate" | "low" | "informational";
          identified_date: string;
          scheduled_completion: string;
          actual_completion: string | null;
          status: "open" | "ongoing" | "completed" | "risk_accepted";
          milestones: Json;
          point_of_contact: string | null;
          resources_required: string | null;
          days_to_sla: number | null;
          sla_status: "ok" | "warning" | "overdue" | "not_applicable";
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          system_id: string;
          finding_id?: string | null;
          poam_number: string;
          weakness_description: string;
          source?: "scan" | "assessment" | "self_identified";
          severity: "high" | "moderate" | "low" | "informational";
          identified_date: string;
          scheduled_completion: string;
          actual_completion?: string | null;
          status?: "open" | "ongoing" | "completed" | "risk_accepted";
          milestones?: Json;
          point_of_contact?: string | null;
          resources_required?: string | null;
          days_to_sla?: number | null;
          sla_status?: "ok" | "warning" | "overdue" | "not_applicable";
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          system_id?: string;
          finding_id?: string | null;
          poam_number?: string;
          weakness_description?: string;
          source?: "scan" | "assessment" | "self_identified";
          severity?: "high" | "moderate" | "low" | "informational";
          identified_date?: string;
          scheduled_completion?: string;
          actual_completion?: string | null;
          status?: "open" | "ongoing" | "completed" | "risk_accepted";
          milestones?: Json;
          point_of_contact?: string | null;
          resources_required?: string | null;
          days_to_sla?: number | null;
          sla_status?: "ok" | "warning" | "overdue" | "not_applicable";
          created_at?: string;
          updated_at?: string;
        };
      };
      deviation_requests: {
        Row: {
          id: string;
          organization_id: string;
          poam_id: string;
          deviation_type: "RA" | "FP" | "OR";
          justification: Json;
          evidence_file_url: string | null;
          requested_by: string;
          requested_date: string;
          status: "draft" | "submitted" | "approved" | "rejected";
          reviewer_id: string | null;
          review_date: string | null;
          review_notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          poam_id: string;
          deviation_type: "RA" | "FP" | "OR";
          justification: Json;
          evidence_file_url?: string | null;
          requested_by: string;
          requested_date?: string;
          status?: "draft" | "submitted" | "approved" | "rejected";
          reviewer_id?: string | null;
          review_date?: string | null;
          review_notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          poam_id?: string;
          deviation_type?: "RA" | "FP" | "OR";
          justification?: Json;
          evidence_file_url?: string | null;
          requested_by?: string;
          requested_date?: string;
          status?: "draft" | "submitted" | "approved" | "rejected";
          reviewer_id?: string | null;
          review_date?: string | null;
          review_notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      scrs: {
        Row: {
          id: string;
          organization_id: string;
          system_id: string;
          title: string;
          description: string;
          change_type: string;
          controls_impacted: string[];
          submitted_date: string | null;
          status:
            | "draft"
            | "submitted"
            | "under_review"
            | "approved"
            | "rejected"
            | "withdrawn";
          approval_date: string | null;
          created_by: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          system_id: string;
          title: string;
          description: string;
          change_type: string;
          controls_impacted?: string[];
          submitted_date?: string | null;
          status?:
            | "draft"
            | "submitted"
            | "under_review"
            | "approved"
            | "rejected"
            | "withdrawn";
          approval_date?: string | null;
          created_by: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          system_id?: string;
          title?: string;
          description?: string;
          change_type?: string;
          controls_impacted?: string[];
          submitted_date?: string | null;
          status?:
            | "draft"
            | "submitted"
            | "under_review"
            | "approved"
            | "rejected"
            | "withdrawn";
          approval_date?: string | null;
          created_by?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      conmon_reports: {
        Row: {
          id: string;
          organization_id: string;
          system_id: string;
          reporting_period_start: string;
          reporting_period_end: string;
          report_file_url: string | null;
          generated_at: string;
          generated_by: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          system_id: string;
          reporting_period_start: string;
          reporting_period_end: string;
          report_file_url?: string | null;
          generated_at?: string;
          generated_by: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          system_id?: string;
          reporting_period_start?: string;
          reporting_period_end?: string;
          report_file_url?: string | null;
          generated_at?: string;
          generated_by?: string;
        };
      };
      audit_log: {
        Row: {
          id: string;
          organization_id: string;
          user_id: string | null;
          action: string;
          entity_type: string;
          entity_id: string;
          diff: Json | null;
          created_at: string;
        };
        // Append-only via Postgres triggers. RLS blocks all direct client writes.
        Insert: {
          id?: string;
          organization_id: string;
          user_id?: string | null;
          action: string;
          entity_type: string;
          entity_id: string;
          diff?: Json | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          user_id?: string | null;
          action?: string;
          entity_type?: string;
          entity_id?: string;
          diff?: Json | null;
          created_at?: string;
        };
      };
      notifications: {
        Row: {
          id: string;
          organization_id: string;
          user_id: string;
          type:
            | "sla_warning"
            | "sla_overdue"
            | "deviation_submitted"
            | "deviation_reviewed"
            | "scan_uploaded";
          title: string;
          body: string;
          entity_type: string | null;
          entity_id: string | null;
          read_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          user_id: string;
          type:
            | "sla_warning"
            | "sla_overdue"
            | "deviation_submitted"
            | "deviation_reviewed"
            | "scan_uploaded";
          title: string;
          body: string;
          entity_type?: string | null;
          entity_id?: string | null;
          read_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          user_id?: string;
          type?:
            | "sla_warning"
            | "sla_overdue"
            | "deviation_submitted"
            | "deviation_reviewed"
            | "scan_uploaded";
          title?: string;
          body?: string;
          entity_type?: string | null;
          entity_id?: string | null;
          read_at?: string | null;
          created_at?: string;
        };
      };
    };
    Views: Record<string, never>;
    Functions: {
      next_poam_sequence: {
        Args: { p_system_id: string };
        Returns: number;
      };
      create_poam_from_finding: {
        Args: {
          p_finding_id: string;
          p_system_id: string;
          p_weakness: string;
          p_severity: "high" | "moderate" | "low" | "informational";
          p_identified: string;
        };
        Returns: string | null;
      };
      recalculate_sla: {
        Args: Record<string, never>;
        Returns: void;
      };
    };
    Enums: {
      user_role: "admin" | "issm" | "isso" | "engineer" | "auditor";
      fedramp_level: "Low" | "Moderate" | "High";
      system_status: "active" | "sunset";
      scan_type: "os" | "webapp" | "database";
      severity_level: "high" | "moderate" | "low" | "informational";
      finding_status:
        | "open"
        | "remediated"
        | "deviation_pending"
        | "deviation_approved"
        | "risk_accepted";
      poam_source: "scan" | "assessment" | "self_identified";
      poam_status: "open" | "ongoing" | "completed" | "risk_accepted";
      deviation_type: "RA" | "FP" | "OR";
      deviation_status: "draft" | "submitted" | "approved" | "rejected";
      scr_status:
        | "draft"
        | "submitted"
        | "under_review"
        | "approved"
        | "rejected"
        | "withdrawn";
      notification_type:
        | "sla_warning"
        | "sla_overdue"
        | "deviation_submitted"
        | "deviation_reviewed"
        | "scan_uploaded";
    };
  };
};
