/**
 * OSCAL POA&M builder — NIST OSCAL 1.1.2 / FedRAMP Rev 5.
 *
 * Produces a valid OSCAL Plan of Action and Milestones JSON document
 * suitable for submission to the FedRAMP PMO or import into GRC tools.
 *
 * Reference: https://pages.nist.gov/OSCAL/reference/latest/plan-of-action-and-milestones/
 */

import { randomUUID } from "crypto";

// ---------------------------------------------------------------------------
// Input shape (populated from DB query in the API route)
// ---------------------------------------------------------------------------

export type OscalMilestone = {
  id:          string;
  description: string;
  target_date: string; // ISO date
  completed:   boolean;
};

export type OscalPoamItem = {
  id:                   string;  // UUID
  poamNumber:           string;  // "V-XYZ-0001"
  weakness:             string;
  severity:             "high" | "moderate" | "low" | "informational";
  status:               string;
  scheduledCompletion:  string;  // ISO date
  identifiedDate:       string;  // ISO date
  slaStatus:            string;
  daysToSla:            number | null;
  controlIds:           string[];
  milestones:           OscalMilestone[];
};

export type OscalPoamInput = {
  systemId:    string;
  systemName:  string;
  orgName:     string;
  fedrampLevel: string;
  generatedAt: string; // ISO datetime
  items:       OscalPoamItem[];
};

// ---------------------------------------------------------------------------
// OSCAL document type (structural, not exhaustive)
// ---------------------------------------------------------------------------

type OscalDocument = {
  "plan-of-action-and-milestones": {
    uuid: string;
    metadata: {
      title:           string;
      "last-modified": string;
      version:         string;
      "oscal-version": string;
      parties: {
        uuid:  string;
        type:  string;
        name:  string;
      }[];
      remarks: string;
    };
    "import-ssp": { href: string };
    "system-id":  { "identifier-type": string; "#text": string };
    "local-definitions": {
      remarks: string;
    };
    "poam-items": unknown[];
  };
};

// ---------------------------------------------------------------------------
// Builder
// ---------------------------------------------------------------------------

export function buildOscalPoam(input: OscalPoamInput): OscalDocument {
  const docUuid = randomUUID();
  const orgUuid = randomUUID();

  return {
    "plan-of-action-and-milestones": {
      uuid: docUuid,
      metadata: {
        title:           `FedRAMP POA&M — ${input.systemName}`,
        "last-modified": input.generatedAt,
        version:         "1.0",
        "oscal-version": "1.1.2",
        parties: [
          {
            uuid: orgUuid,
            type: "organization",
            name: input.orgName,
          },
        ],
        remarks: `Generated by ConMon Dashboard. FedRAMP ${input.fedrampLevel} system.`,
      },
      "import-ssp": {
        href: `#system-${input.systemId}`,
      },
      "system-id": {
        "identifier-type": "https://fedramp.gov",
        "#text":            input.systemId,
      },
      "local-definitions": {
        remarks: "POA&M items exported from ConMon continuous monitoring dashboard.",
      },
      "poam-items": input.items.map((item) => buildPoamItem(item)),
    },
  };
}

function buildPoamItem(item: OscalPoamItem): unknown {
  const riskUuid        = randomUUID();
  const remediationUuid = randomUUID();

  // FedRAMP-specific OSCAL properties
  const props: { name: string; ns: string; value: string }[] = [
    { name: "poam-id",    ns: "https://fedramp.gov/ns/oscal", value: item.poamNumber },
    { name: "severity",   ns: "https://fedramp.gov/ns/oscal", value: item.severity },
    { name: "sla-status", ns: "https://fedramp.gov/ns/oscal", value: item.slaStatus },
  ];

  if (item.daysToSla !== null) {
    props.push({
      name:  "days-to-sla",
      ns:    "https://fedramp.gov/ns/oscal",
      value: String(item.daysToSla),
    });
  }

  // Link to NIST 800-53 controls
  const relatedControls =
    item.controlIds.length > 0
      ? {
          "control-selections": item.controlIds.map((cId) => ({
            "include-controls": [{ "control-id": cId.toLowerCase() }],
          })),
        }
      : undefined;

  // Milestones → OSCAL tasks
  const tasks = item.milestones.map((m) => ({
    uuid:   randomUUID(),
    type:   "milestone",
    title:  m.description,
    timing: {
      "within-date-range": {
        start: new Date(m.target_date).toISOString(),
        end:   new Date(m.target_date).toISOString(),
      },
    },
    remarks: m.completed ? "Completed." : "Pending.",
  }));

  return {
    uuid:        item.id,
    title:       item.poamNumber,
    description: item.weakness,
    props,
    ...(relatedControls ? { "related-controls": relatedControls } : {}),

    risks: [
      {
        uuid:        riskUuid,
        title:       `Weakness: ${item.poamNumber}`,
        description: item.weakness,
        statement:   item.weakness,
        status:      item.status === "completed" || item.status === "risk_accepted"
          ? "closed"
          : "open",
        "mitigating-factors": [],
        deadline: new Date(item.scheduledCompletion).toISOString(),
        responses: [
          {
            uuid:      remediationUuid,
            lifecycle: "planned",
            title:     "Remediation",
            description: `Scheduled completion: ${item.scheduledCompletion}`,
            tasks: tasks.length > 0 ? tasks : undefined,
          },
        ],
      },
    ],
  };
}
